Tensors:

- N-D array

- 1D tensor: Vector
- 2D tensor: Matrix
- 3D tensor: Image
- 4D tensor: Video

A 'torch.Tensor' is a data container

- shape: the size of tensor
- dtype: the data type
- ndim: the number of dimensions

In [28]:
import torch
from PIL import Image
import numpy as np

In [29]:
img = Image.open('./data/cat.jpeg')

# convert to tensor
cat = torch.as_tensor(np.array(img)).float()
print(cat.shape)
print(cat.dtype) # uint8 == default for images
print(cat.ndim)

torch.Size([518, 386, 3])
torch.float32
3


pytorch likes to convert numpy arrays to tensors BUT not images

so turn the img into a numpy array

In [30]:
a = torch.arange(10)
b = torch.ones(10)

print(a)
print(b)

print("OPERATIONS")

print(a+b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
OPERATIONS
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [31]:
# tensors cant do operations if theyre diff shapes

a = torch.rand(4)
b = torch.rand(5)

# print(a+b)

In [32]:
a = torch.rand(1_000_000_000)
b = torch.rand(1_000_000_000)

In [33]:
%timeit c = a + b

166 ms ± 87.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [35]:
# try this with a machine with a gpu
# but the idea is that it should be quicker than the operation a cell above

# a_cuda = a.to("cuda")
# b_cuda = a.to("cuda")

# %timeit c_cuda = a_cuda + b_cuda