In [171]:
import torch
import torch.distributions as dist

In [172]:
# ceate a Bernoulli distribution

bernoulli = dist.Bernoulli(torch.tensor([0.5]))
# print(bernoulli)

# Sample from the distribution
for i in range(10):
    print(bernoulli.sample())

tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([1.])


In [173]:
samples = [bernoulli.sample() for i in range(1000)]
torch.stack(samples) # stacks tensors on top of each other

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

In [174]:
print(f"Mean: {torch.mean(torch.stack(samples))}")

Mean: 0.5009999871253967


In [175]:
print(f"var: {torch.var(torch.stack(samples))}")

var: 0.2502492368221283


In [176]:
# create a Normal distribution
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0])) # (mean, std)

for i in range(10):
    print(normal.sample())

tensor([1.2882])
tensor([0.7597])
tensor([2.0872])
tensor([0.2931])
tensor([0.4818])
tensor([1.2990])
tensor([-0.9907])
tensor([-1.6006])
tensor([-0.0919])
tensor([-0.9073])


In [177]:
samples = [normal.sample() for i in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"var: {torch.var(torch.stack(samples))}")

Mean: -0.0059372251853346825
var: 0.9569777846336365


## In sampling any prob distribution, the samples NEVER FULLY MATCH the ORIGINAL Distribution !!!!

So the examples above shows that, where each output is never the same and is very close to the given mean tensor but never the exact same